# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "checkout-delivery-instructions"
client_id = "026ca25965f58f63888fc39d8bbcdb6e"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
dev_store_url = "kasdeveloper.myshopify.com"
